### ISSUE TITLE
Ruby : Document symbol information not available for 'd:\viz\script\import_scripts\mbox\support\indexer.rb'

### ISSUE THREAD

**Issue by Suraj-1999-13** [chanhx/crabviz#39] opened 2024-08-07 16:02 UTC
After running the generate call graph for the ruby code base getting the error - Document symbol information not available for 'd:\viz\script\import_scripts\mbox\support\indexer.rb'
![image](https://github.com/user-attachments/assets/772b28ce-de6e-4c02-9743-3212981bae75)

**Comment by Suraj-1999-13** [comment] 2024-08-07 16:03
Also, I have installed the Ruby and Ruby LSP VS Code extension.

**Comment by chanhx** [comment] 2024-08-08 06:01
Did the outline panel show any symbols?

**Comment by Suraj-1999-13** [comment] 2024-08-10 08:34
After installing the 'ruby symbol' extension it started the showing outline but the generated graph does not have any call graph between different ruby files.

**Comment by chanhx** [comment] 2024-08-10 12:36
Hmm, I guess the ruby extension doesn't support Call Hierarchy. If so, Crabviz can't draw edges. You can confirm it by right clicking a function, see if there is a "Show Call Hierarchy" option on the context menu.

**Comment by chaseschuette** [comment] 2024-12-05 15:59
I also received this error when ran on a directory of bash scripts while excluding a few python scripts.

**Comment by chanhx** [comment] 2024-12-09 08:23
> I also received this error when ran on a directory of bash scripts while excluding a few python scripts.

Crabviz relies on the Code Outline and Call Hierarchy features provided by language servers to draw call graphs. If you get the "document symbol information not available" error, probably the Code Outline feature is not supported, you can check the outline panel to confirm it.

FYI, I found the `Bash IDE` extension supports the Code Outline feature, but according to its README, it seems it doesn't support the Call Hierarchy feature (not sure), and I didn't find other bash extensions support that feature. So, Hmmm...

**Comment by chanhx** [comment] 2024-12-10 11:47
Closing this issue as it's not a bug.

**Closed as completed by chanhx** 2024-12-10 11:47 UTC
